### ISSUE TITLE
Käytettyjen kirjastojen lisenssien läpikäynti

### ISSUE THREAD

**Issue by kordaniel** [Konenako/Ohtuprojekti-kesa2020#107]

**Comment by kordaniel** [comment]
Voidaanko kaikkia kirjastoja käyttää, miten vaikuttaa meidän lisenssiin jne? Pitäisikö ehkä tehdä selkeä dokumentaatio, esim. lista mikä on helpompi käydä läpi kuin poetry/apt/ymt tiedostot, minne kerätään kaikki?

**Comment by Teo44** [comment]
Kävin lisenssit läpi, eikä mitään ongelmia näytä olevan. Docutils ja pylint käyttää GPL lisenssiä, joka [ei ole yhteensopiva monien lisenssien kanssa](https://www.gnu.org/licenses/license-list.html), mutta kaikki meidän kirjastoista kyllä käyvät.
