### ISSUE TITLE
Yapf automatisoinnin mahdollisuuksien selvitys

### ISSUE THREAD

**Issue by ArktinenKarpalo** [Konenako/Ohtuprojekti-kesa2020#108]

**Comment by JoakimJoensuu** [comment]
Kuulostaisko ihan hullulta, jos circleci suorittais tästä oman commitin?
CircleCIlle vois antaa ympäristömuutujana esim salasanan tms

**Comment by ArktinenKarpalo** [comment]
https://github.com/google/yapf/blob/master/plugins/pre-commit.sh
git ja yapf vaikuttaa olevan jotain valmiita ratkaisuja tähän (täytyy tutkia linkattu myöhemmin tarkemmin)

**Comment by JoakimJoensuu** [comment]
Samalla vois lisätä toiminnallisuuden, joka estää suoraa masteriin puskemisen.

https://github.com/DataBiosphere/data-explorer/blob/master/hooks/pre-commit

**Comment by JoakimJoensuu** [comment]
[https://github.com/Konenako/Ohtuprojekti-kesa2020/commit/117d61b143628f6993f334fdd428d0a8715939c3](https://github.com/Konenako/Ohtuprojekti-kesa2020/commit/117d61b143628f6993f334fdd428d0a8715939c3)

Tällä alkeellisella viritelmällä onnistu CircleCIstä samaan branchiin puskeminen.
Tohon kun laittaa jonkun ehdon, että jos yapf ei mee läpi, niin tekee tavittavat komennot koodin formatoinnille ja puskee uuden commitin

**Comment by kordaniel** [comment]
Nyt toimii iffi, eli jos yapf ei mene läpi, niin circleci ajaa formatoinnin ja tekee uuden commitin. Tuossa on vain se ikävä asia nyt, että vaikka tuo ei-nolla exit-code tulee iffissä, niin CircleCI lopettaa ajon siihen paikkaan ilman tuota 'set +e' komentoa. Eli tuollaisenaan sitä ei voi päästää masteriin, koska testit menee läpi tuli sitten mikä tahansa virheilmo missä tahansa käsittääkseni.

Lisäksi ilmeisesti poetry run palauttaa ajettavan komennon exit-coden, eli ei tarvita noita monimutkaisia komentoja putkineen. Eli tuosta 'set +e' -komennosta olisi varmaan päästävä eroon, CircleCI:llä taitaa olla jotain vaihtoehtoja tuohon kyllä.

Lisäksi, olisiko parempi jos CircleCI päivittäisi sen commitin mitä se tarkistaa sen sijaan että tekee uuden? Vaikka samalla commmit-viestillä johon lisätään tuo formatted by CircleCI yapf?
[Muutokset rivistä 33 eteenpäin](https://github.com/Konenako/Ohtuprojekti-kesa2020/blob/circleci_yapf_automation/.circleci/config.yml)
