### ISSUE TITLE
Kovakoodattujen muuttujien korvaaminen argumenteilla

### ISSUE THREAD

**Issue by Teo44** [Konenako/Ohtuprojekti-kesa2020#132]

**Comment by Teo44** [comment]
Ihan alkuun pitänee määritellä yhtenäinen tyyli mitä argumentit käyttää. Esim:
mallin nimi: -m --model
label tiedosto: -l --labels
tunnistuksen taajuus: -f --frequency
kameran/videon polku: -c --camera
julkaisutopicin nimi (?): -p --publish-topic
videotopicin nimi (?): -i --input-topic
käynnistä node tunnistus pysäytettynä (?): -s --stopped

**Comment by JoakimJoensuu** [comment]
Mun mielestä selkeät.
Näille tulee varmaan jotku default arvot sit?

**Comment by ArktinenKarpalo** [comment]
Topicien nimet on varmaan turhia, muuten näyttää hyvältä.

**Comment by Teo44** [comment]
> 
> 
> Mun mielestä selkeät.
> Näille tulee varmaan jotku default arvot sit?

Kaikelle muulle paitsi mallille kyllä, mutta minkään mallin tiedostonimeä ei viittis kovakoodata. Sitten kun on malleille oma kansio joka myös kiinnitetään kontteihin niin defaulttina voisi napata sieltä ensimmäisen tiedoston?

**Comment by JoakimJoensuu** [comment]
> > Mun mielestä selkeät.
> > Näille tulee varmaan jotku default arvot sit?
> 
> Kaikelle muulle paitsi mallille kyllä, mutta minkään mallin tiedostonimeä ei viittis kovakoodata. Sitten kun on malleille oma kansio joka myös kiinnitetään kontteihin niin defaulttina voisi napata sieltä ensimmäisen tiedoston?

Jos se ottaa ekan mallin, niin sille pitäis sit löytää kans sitä vastaava label tiedosto?

Ehkä malli ja labelit pitää jättää pakollisiks parametreiks

**Comment by Teo44** [comment]
Mennään sitten tälla listalla ainakin toistaiseksi:
mallin nimi (pakollinen): -m --model
label tiedosto (pakollinen): -l --labels
tunnistuksen taajuus: -f --frequency
kameran/videon polku: -c --camera
käynnistä node tunnistus pysäytettynä (?): -s --stopped

**Comment by Teo44** [comment]
Nykyiset parametrit lisätty [ROS dokkariin.](https://docs.google.com/document/d/1ZX2D-lR2-JPhgsHoDeP2K5ocj3jB0FU43SoIwdkePvU/edit#)
