### ISSUE TITLE
ID image ja observations viesteille, josta tietää mistä framesta tunnistus on tehty.

### ISSUE THREAD

**Issue by Teo44** [Konenako/Ohtuprojekti-kesa2020#138]

**Comment by JoakimJoensuu** [comment]
Tää ID on varmaa kamerakohtanen ja se vaan liitetään imageen ja observationeihin?

**Comment by Teo44** [comment]
> Tää ID on varmaa kamerakohtanen ja se vaan liitetään imageen ja observationeihin?
> 
> Vai tuleeko jokaselle framelle ihan omat ID:t

Jos ID:tä ei erikseen anneta, niin sitten jokaiselle framelle oma ID juoksevalla numeroinnilla, kuten asiakas halus. Lisäksi vois kyllä olla kamerakohtainen tunniste, ainakin jos useampaa kameraa käytettäessä ne julkaisee samaan topicciin.
