### ISSUE TITLE
TF tulosten filtteröinti ja järjestäminen

### ISSUE THREAD

**Issue by Teo44** [Konenako/Ohtuprojekti-kesa2020#150]

**Comment by ArktinenKarpalo** [comment]
Lieneekö välttämättä kovin tarpeellinen ominaisuus? Helpompaa melkein että asiakkaat omassa koodissa vetää havainnot jonkin filtterin läpi.

**Comment by Teo44** [comment]
Tuleehan siinä turhaa koodia, kun pitää viestiä meidän nodelle mitkä labelit hyväksytään. Viime asiakaspalaverista toi on toinen kahdesta tummennetusta kohdasta muistiinpanoissa, mutta itse en kyllä muista että asiakas olisi pahemmin painottanut tätä.

**Comment by Teo44** [comment]
+ tulosten järjestäminen class_id tai score mukaan (käyttäjän valittavissa)
