### ISSUE TITLE
README ohjeet ajan tasalle

### ISSUE THREAD

**Issue by JoakimJoensuu** [Konenako/Ohtuprojekti-kesa2020#184]
https://github.com/Konenako/Ohtuprojekti-kesa2020/tree/README_update

**Comment by JoakimJoensuu** [comment]
Ohjeet yksittäisten nodejen käynnistämiselle roslaunchilla ei nyt toimi. Mikäköhän avuks?

**Comment by kordaniel** [comment]
> Ohjeet yksittäisten nodejen käynnistämiselle rosrunilla ei nyt toimi. Kaikki muut pitäs toimia ohjeilla Mikäköhän avuks?

Tämä taitaa johtua siitä, että test.launchissa asetetaan group_ns='konenako' ja kaikki rosparametrit menevät sen alle. Jos ajaa roslaunchilla, niin nodet osaavat lisätä sen haettuihin rosparametreihin toisin kuin jos nodet ajetaan rosrunnilla.

Selkeämmin:
Jos ajetaan roslaunchilla, niin cameranode esim. hakee /konenako/video_source ja jos ajetaan rosrunilla, niin sama node hakee pelkkää /video_source:a.

Olisikohan ROS:illa joku funktio miltä voisi kysyä, että onko node ajettu roslaunchin kautta tai suoraan että onko group_ns asetettu?
