### ISSUE TITLE
observations.msg viestiin metadata kenttä (JSON muotoinen dictionary?)

### ISSUE THREAD

**Issue by Teo44** [Konenako/Ohtuprojekti-kesa2020#197]
Tieto siitä onko kuvaa yritetty tunnistaa, ehkä myös kuvan ulottuvuudet tänne

**Comment by Teo44** [comment]
Palaverista:
* observations.msg “metadata”-kenttä: onko yritetty tunnistaa/ei olla/ei ehditty
  * voidaan lisätä kuvan id, koko ja muuta
  * JSON muotoinen string joka voidaan parsia dictionaryksi (tai joku muu vastaava paljon käytetty)
  * http://wiki.ros.org/rospy_message_converter

**Comment by kordaniel** [comment]
Tällä hetkellä QR-detectorin data, eli qr-koodin sisältö menee label-kenttään, samoin kuin object-detectorin "label". Jos halutaan filtteröidä/järjestää labelin mukaan, niin tämä lisää kompleksisuutta aika reilust kun joudutaan ottamaan huomioon observation_type kenttä erikseen.

Ehkä observations.msg:hen voisi samalla lisätä data-kentän, minne voi tallentaa qr-koodin sisällön? Ja tällöin QR-detectori voisi käyttää labelia 'QR' tmv?
