### ISSUE TITLE
Selvitä kumpi tehokkaampi, topic vai service jatkuville datavirroille

### ISSUE THREAD

**Issue by JoakimJoensuu** [Konenako/Ohtuprojekti-kesa2020#65]
[https://github.com/Konenako/Ohtuprojekti-kesa2020/issues/65#issuecomment-639316750](https://github.com/Konenako/Ohtuprojekti-kesa2020/issues/65#issuecomment-639316750)

**Comment by Teo44** [comment]
rostestin "observations" topicin voisi ehkä korvata servicellä, jos riittää että havainnot lähetetään vain asiakkaan "aivo"-nodelle. Onko serviceen vaihtamisesta merkittävää hyötyä? [Tämän ](https://wiki.ros.org/ROS/Patterns/Communication#Communication_via_Topics_vs_Services_vs_X)mukaan jatkuviin datavirtoihin (kuten havainnot) kannattaisi käyttää topicceja, ja servicejä yksittäisiin kutsuihin (kameranoden konffaaminen käynnistäessä?)

**Comment by JoakimJoensuu** [comment]
@Teo44 
Toi ois kyllä ihan testaamisen arvosta. Uus taski?
