### ISSUE TITLE
Selkeä dokumentaatio API:sta, eli tuetuista ROS service/topiceista

### ISSUE THREAD

**Issue by kordaniel** [Konenako/Ohtuprojekti-kesa2020#83]

**Comment by JoakimJoensuu** [comment]
Muista listata nimet tarkasti!

**Comment by Teo44** [comment]
Nykyinen versio, ei ole paljon listattavaa vielä, kun print ja input nodetkin ovat vaan kehitystä varten.

https://docs.google.com/document/d/1ZX2D-lR2-JPhgsHoDeP2K5ocj3jB0FU43SoIwdkePvU/edit#
